channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab >=3.1,<4 # the docs specify this, but the metadata doesn't
  - plotly              # might as well have mamba do this
  - pip
  - pip:
    - webio-jupyter-extension
